### ISSUE TITLE
Can't attach ACL to VLAN interface

### ISSUE THREAD

**Issue by mcallisterjp** [open-switch/opx-cps#63]
I'm using IN_INTF/OUT_INTF for ACL match rules that want to match on an ingress/egress interface, but this match type doesn't work for VLANs or LAGs.

Out of the other match rules, SRC_PORT/DST_PORT don't work:
```
void nas_acl_table::set_allowed_filter(uint_t) (), Unknown Table Match Field type 34
Feb 23 10:55:45 opx_vm python[14002]: [DSAPI:COMMIT], Failed to commit request at 0 out of 1
```

And it's not clear how the concepts in the others relate to interface types. How should this be configured in CPS? Or is it not possible?

**Comment by atanu-mandal** [comment]
Can you please use OUTER_VLAN_ID to attach the ACL to VLAN.

**Comment by mcallisterjp** [comment]
Atanu,

Presumably OUTER_VLAN_ID only works for VLAN-tagged packets? Is there an answer for untagged VLAN interfaces? Or for LAGs?

**Comment by atanu-mandal** [comment]
Hi Pete, OUTER_VLAN_ID should be applicable for untagged VLAN as well, in that case PVID  will be used.
In the current version it does not seem to have full support for LAG as a match-type, we can use the LAG's member port(ports) into IN_PORT (IN_PORTS) classifier. 
Hope that helps.

**Comment by atanu-mandal** [comment]
Hi Pete, also looks like (from the log) you are trying this on a VM target where we are not having much support for ACL. I would suggest to try the ACL configuration on real hardware.

**Comment by atanu-mandal** [comment]
Please try LAG interface as SRC_INTF/OUT_INTF filter type in INGRESS stage, that should be working. Let us know if you face any issue.

**Comment by dimbleby** [comment]
Hi, 

There are several things going on in this one!

* `SRC_INTF` works fine on a LAG interface, so that's great - thank you
* `OUT_INTF` does not work on a LAG interface
  * The configuration is accepted, but ineffective
  * However since we don't yet have it working on plain ethernet interfaces either - per #65 - that's probably not surprising
   * Let's get #65 resolved first, and then revisit
* We haven't yet tested matching on `OUTER_VLAN_ID`
  * For the purposes of this issue, I think we can leave it at "matching on a VLAN interface is not supported" - and in due course we should expect to use the `OUTER_VLAN_ID` match instead.

So I think all that's left here is getting `OUT_INTF` working on LAG interfaces.  I'm happy to handle that either under #65 or here, whichever you prefer.

**Comment by atanu-mandal** [comment]
OUT_INTF should work for both ingress and egress stages. But for egress stage, LAG interface is not supported. Please check the comments under #65.

**Comment by dimbleby** [comment]
All that was left in this one was matching on outbound ACL interfaces - and this seems to be the same as #65.  Closing.

**Comment by atanu-mandal** [comment]
Based on above comments I am closing this one. Please reopen if you find any issue.
